services:
  dozzle:
    container_name: abes-docker-dozzle
    image: amir20/dozzle:v11.1.0-alpine
    restart: unless-stopped
    mem_limit: ${DOZZLE_MEM_LIMIT}
    memswap_limit: ${DOZZLE_MEMSWAP_LIMIT}
    cpus: ${DOZZLE_CPU_LIMIT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${DOZZLE_PORT_WEB}:8080
      - ${DOZZLE_PORT_DOCKER_DAEMON}:2375
